[2024-05-24T00:21:00.957+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-24T00:21:00.968+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.load_Co2_Concentration_Data manual__2024-05-24T00:20:57.409182+00:00 [queued]>
[2024-05-24T00:21:00.971+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.load_Co2_Concentration_Data manual__2024-05-24T00:20:57.409182+00:00 [queued]>
[2024-05-24T00:21:00.972+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-24T00:21:00.977+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_Co2_Concentration_Data> on 2024-05-24 00:20:57.409182+00:00
[2024-05-24T00:21:00.981+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=216) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-24T00:21:00.981+0000] {standard_task_runner.py:63} INFO - Started process 221 to run task
[2024-05-24T00:21:00.982+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'load_Co2_Concentration_Data', 'manual__2024-05-24T00:20:57.409182+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/***_dag.py', '--cfg-path', '/tmp/tmp4a0f8bll']
[2024-05-24T00:21:00.982+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask load_Co2_Concentration_Data
[2024-05-24T00:21:01.000+0000] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline.load_Co2_Concentration_Data manual__2024-05-24T00:20:57.409182+00:00 [running]> on host 7f18484bb9a3
[2024-05-24T00:21:01.044+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='load_Co2_Concentration_Data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-24T00:20:57.409182+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-24T00:20:57.409182+00:00'
[2024-05-24T00:21:01.044+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-24T00:21:01.045+0000] {log.py:232} WARNING - [2024-05-24 00:21:01,045] [INFO] - Database CombinedDataset.sqlite did not exist and was created.
[2024-05-24T00:21:01.045+0000] {base_logger.py:19} INFO - Database CombinedDataset.sqlite did not exist and was created.
[2024-05-24T00:21:01.129+0000] {log.py:232} WARNING - [2024-05-24 00:21:01,129] [INFO] - Data from ./data/transformed/Solar_Flare_Data.csv loaded into Solar_Flare_Data table in CombinedDataset.sqlite database.
[2024-05-24T00:21:01.129+0000] {base_logger.py:19} INFO - Data from ./data/transformed/Solar_Flare_Data.csv loaded into Solar_Flare_Data table in CombinedDataset.sqlite database.
[2024-05-24T00:21:01.130+0000] {log.py:232} WARNING - [2024-05-24 00:21:01,129] [INFO] - Connection to CombinedDataset.sqlite closed.
[2024-05-24T00:21:01.129+0000] {base_logger.py:19} INFO - Connection to CombinedDataset.sqlite closed.
[2024-05-24T00:21:01.130+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-24T00:21:01.130+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-24T00:21:01.135+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=load_Co2_Concentration_Data, run_id=manual__2024-05-24T00:20:57.409182+00:00, execution_date=20240524T002057, start_date=20240524T002100, end_date=20240524T002101
[2024-05-24T00:21:01.154+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-24T00:21:01.166+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-24T00:21:01.168+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
