[2024-05-24T00:18:32.300+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-24T00:18:32.312+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.extract_Temperature_Data manual__2024-05-24T00:18:30.441951+00:00 [queued]>
[2024-05-24T00:18:32.316+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.extract_Temperature_Data manual__2024-05-24T00:18:30.441951+00:00 [queued]>
[2024-05-24T00:18:32.316+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-24T00:18:32.324+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_Temperature_Data> on 2024-05-24 00:18:30.441951+00:00
[2024-05-24T00:18:32.327+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=120) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-24T00:18:32.327+0000] {standard_task_runner.py:63} INFO - Started process 129 to run task
[2024-05-24T00:18:32.328+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'extract_Temperature_Data', 'manual__2024-05-24T00:18:30.441951+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/***_dag.py', '--cfg-path', '/tmp/tmpryx6or1m']
[2024-05-24T00:18:32.328+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask extract_Temperature_Data
[2024-05-24T00:18:32.347+0000] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline.extract_Temperature_Data manual__2024-05-24T00:18:30.441951+00:00 [running]> on host 7f18484bb9a3
[2024-05-24T00:18:32.385+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='extract_Temperature_Data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-24T00:18:30.441951+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-24T00:18:30.441951+00:00'
[2024-05-24T00:18:32.386+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-24T00:18:33.450+0000] {log.py:232} WARNING - [2024-05-24 00:18:33,450] [INFO] - Data extracted and saved to: ./data/raw/
[2024-05-24T00:18:33.450+0000] {base_logger.py:19} INFO - Data extracted and saved to: ./data/raw/
[2024-05-24T00:18:33.451+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-24T00:18:33.451+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-24T00:18:33.456+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=extract_Temperature_Data, run_id=manual__2024-05-24T00:18:30.441951+00:00, execution_date=20240524T001830, start_date=20240524T001832, end_date=20240524T001833
[2024-05-24T00:18:33.501+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-24T00:18:33.506+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
